/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import wFlange from "../../assets/gltf/structure/w-flange.gltf";

export default function Model({ position = [0, 0, 0], ...props }) {
  const group = useRef();

  const { nodes, materials } = useGLTF(wFlange);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
  return <group />;
}

useGLTF.preload(wFlange);
