/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from "react";
import { useGLTF } from "@react-three/drei";
import Instances from "./instances";
import { filterModels } from "./helpers";

import torus from "../../assets/gltf/items/bump-torus-transformed.glb";

const COUNT = 25;
export default function Model({ position = [0, 0, 0], dropCommand, ...props }) {
  const { nodes, materials } = useGLTF(torus);
  return (
    <Instances
      commandStream={dropCommand}
      commandFilterFn={(command) =>
        filterModels("torus", command?.data?.arguments?.input0)
      }
      count={COUNT}
      {...props}
    >
      <instancedMesh
        castShadow
        receiveShadow
        args={[nodes.Torus.geometry, nodes.Torus.material, COUNT]}
        count={COUNT}
      />
    </Instances>
  );
}

useGLTF.preload(torus);
