/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from "react";
import { useGLTF, useMatcapTexture } from "@react-three/drei";
import Instances from "./instances";
import { filterModels } from "./helpers";

import chair from "../../assets/gltf/items/chair-transformed.glb";

const COUNT = 25;
export default function Model({ position = [0, 0, 0], dropCommand, ...props }) {
  const [matcap] = useMatcapTexture(
    // "617586_23304C_1B1E30_4988CF"
    "331A0B_B17038_7D4E28_5B351A", // index of the matcap texture https://github.com/emmelleppi/matcaps/blob/master/matcap-list.json
    1024 // size of the texture ( 64, 128, 256, 512, 1024 )
  );

  const { nodes } = useGLTF(chair);
  return (
    <Instances
      commandStream={dropCommand}
      commandFilterFn={(command) =>
        filterModels("chair", command?.data?.arguments?.input0)
      }
      count={COUNT}
      {...props}
    >
      <instancedMesh
        castShadow
        receiveShadow
        args={[nodes.Chair.geometry, undefined, COUNT]}
        count={COUNT}
      >
        <meshMatcapMaterial matcap={matcap} />
      </instancedMesh>
    </Instances>
  );
}

useGLTF.preload(chair);
