/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import Instances from "./instances";
import { filterModels } from "./helpers";

import cup from "../../assets/gltf/items/cup-transformed.glb";

const COUNT = 25;
export default function Model({ position = [0, 0, 0], dropCommand, ...props }) {
  const { nodes, materials } = useGLTF(cup);
  return (
    <Instances
      commandStream={dropCommand}
      commandFilterFn={(command) =>
        filterModels("cup", command?.data?.arguments?.input0)
      }
      count={COUNT}
      {...props}
    >
      <instancedMesh
        castShadow
        receiveShadow
        args={[nodes.Cup.geometry, materials.Material, COUNT]}
        count={COUNT}
      />
    </Instances>
  );
}

useGLTF.preload(cup);
