/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import Instances from "./instances";
import { filterModels } from "./helpers";

import wFlange from "../../assets/gltf/structure/w-flange.gltf";

const COUNT = 25;
export default function Model({ position = [0, 0, 0], dropCommand, ...props }) {
  const { nodes, materials } = useGLTF(wFlange);
  return (
    <Instances
      commandStream={dropCommand}
      commandFilterFn={(command) =>
        filterModels("column", command?.data?.arguments?.input0) ||
        filterModels("beam", command?.data?.arguments?.input0)
      }
      count={COUNT}
      {...props}
    >
      <instancedMesh
        castShadow
        receiveShadow
        args={[nodes.Plane.geometry, materials["Material.001"], COUNT]}
        count={COUNT}
      />
    </Instances>
  );
}

useGLTF.preload(wFlange);
